version: '3.1'

services:
  notebook:
    image: microns-phase3-nda-notebook
    build:
      context: .
    env_file: .env
    volumes:
      - ${EXTERNAL_NOTEBOOKS}:/notebooks/workspace
    ports:
      - "${NOTEBOOK_PORT:-8888}:8888" # Jupyter notebook, defaults to port 8888 unless overridden by the NOTEBOOK_PORT env variable

  database:
    image: microns-phase3-nda-db-v3:latest
    # image: database_container_image_v3:latest # This image should be first loaded from the downloaded tar file, reference SETUP.md for more information.
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=2147483648
    restart: always
    network_mode: 'host'